services:
  app:
    build: .
    volumes:
      - .:/app
    network_mode: host
    environment:
      - PORT=9101

  3x-ui:
    image: ghcr.io/mhsanaei/3x-ui:latest
    container_name: 3x-ui
    ports:
      - "2053:2053"
    volumes:
      - ./db/:/etc/x-ui/
      - ./cert/:/root/cert/
    environment:
      XRAY_VMESS_AEAD_FORCED: "false"
      X_UI_ENABLE_FAIL2BAN: "true"
    
    tty: true
    restart: unless-stopped